import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-white py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms &amp; Conditions</h1>
        <p className="text-sm text-gray-600 mb-8">Updated at January 1st, 2026</p>

        <div className="space-y-8 text-gray-700">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">General Terms</h2>
            <p className="mb-4">
              By accessing and placing an order with Bid The Bezel, you confirm that you are in agreement with and bound by the terms of service contained in the Terms &amp; Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Bid The Bezel.
            </p>
            <p>
              Under no circumstances shall Bid The Bezel team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Bid The Bezel team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
            </p>
            <p className="mt-4">
              Bid The Bezel will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">License</h2>
            <p className="mb-4">
              Bid The Bezel grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
            </p>
            <p>
              These Terms &amp; Conditions are a contract between you and Bid The Bezel (referred to in these Terms &amp; Conditions as "Bid The Bezel", "us", "we" or "our"), the provider of the Bid The Bezel website and the services accessible from the Bid The Bezel website (which are collectively referred to in these Terms &amp; Conditions as the "Bid The Bezel Service").
            </p>
            <p className="mt-4">
              You are agreeing to be bound by these Terms &amp; Conditions. If you do not agree to these Terms &amp; Conditions, please do not use the Bid The Bezel Service. In these Terms &amp; Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms &amp; Conditions, we reserve the right to cancel your account or block access to your account without notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Definitions and key terms</h2>
            <p className="mb-4">To help explain things as clearly as possible in this Terms &amp; Conditions, every time any of these terms are referenced, are strictly defined as:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
              <li><strong>Company:</strong> when this terms mention "Company," "we," "us," or "our," it refers to B Wilder LLC, (150 Seabreeze Blvd Inlet Beach, FL 32461), that is responsible for your information under this Terms &amp; Conditions.</li>
              <li><strong>Country:</strong> where Bid The Bezel or the owners/founders of Bid The Bezel are based, in this case is United States</li>
              <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Bid The Bezel and use the services.</li>
              <li><strong>Service:</strong> refers to the service provided by Bid The Bezel as described in the relative terms (if available) and on this platform.</li>
              <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
              <li><strong>Website:</strong> Bid The Bezel's site, which can be accessed via this URL: bidthebezel.com</li>
              <li><strong>You:</strong> a person or entity that is registered with Bid The Bezel to use the Services.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Restrictions</h2>
            <p className="mb-4">You agree not to, and you will not permit others to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
              <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Bid The Bezel or its affiliates, partners, suppliers or the licensors of the website.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Payment</h2>
            <p className="mb-4">
              If you register to any of our recurring payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time that each fee or charge is due and payable. Unless otherwise indicated in an order form, you must provide Bid The Bezel with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) ("Payment Provider") as a condition to signing up for the Premium plan.
            </p>
            <p className="mb-4">
              Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider. By providing Bid The Bezel with your credit card number and associated payment information, you agree that Bid The Bezel is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to Bid The Bezel hereunder and that no additional notice or consent is required.
            </p>
            <p className="mb-4">
              You agree to immediately notify Bid The Bezel of any change in your billing address or the credit card used for payment hereunder. Bid The Bezel reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization's administrator(s).
            </p>
            <p className="mb-4">
              Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts shall be the responsibility of and paid for by you.
            </p>
            <p>
              No contract will exist between you and Bid The Bezel for the Service until Bid The Bezel accepts your order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication.
            </p>
            <p className="mt-4">
              You are responsible for any third-party fees that you may incur when using the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Return and Refund Policy</h2>
            <p className="mb-4">
              Thanks for shopping at Bid The Bezel. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products.
            </p>
            <p className="mb-4">
              As with any shopping experience, there are terms and conditions that apply to transactions at Bid The Bezel. We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Bid The Bezel, you agree to the terms along with Bid The Bezel's Privacy Policy.
            </p>
            <p>
              If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Your Suggestions</h2>
            <p>
              Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Bid The Bezel with respect to the website shall remain the sole and exclusive property of Bid The Bezel.
            </p>
            <p className="mt-4">
              Bid The Bezel shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Your Consent</h2>
            <p>
              We've updated our Terms &amp; Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms &amp; Conditions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Links to Other Websites</h2>
            <p className="mb-4">
              This Terms &amp; Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by Bid The Bezel. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us.
            </p>
            <p>
              Please remember that when you use a link to go from the Services to another website, our Terms &amp; Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Cookies</h2>
            <p className="mb-4">
              Bid The Bezel uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use.
            </p>
            <p className="mb-4">
              However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
            <p className="mb-4">Don't hesitate to contact us if you have any questions.</p>
            <ul className="space-y-2">
              <li><strong>Via Email:</strong> zack@bidthebezel.com</li>
              <li><strong>Via Phone number:</strong> 438-238-1122</li>
              <li><strong>Via this Address:</strong> Inlet Beach, Florida</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
