type Step =
  | "login"
  | "register"
  | "otp-register"
  | "username"
  | "purchase-plan"
  | "plan-selected"
  | "subscription-confirmation"
  | "sale-type"
  | "personal-detail-auction"
  | "personal-detail-fixed"
  | "authenticate"
 | "shipping"
 | "payment-done"
| "watch-listed"