import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-white py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Privacy Policy</h1>
        <p className="text-sm text-gray-600 mb-8">Updated at January 1st, 2026</p>

        <div className="space-y-8 text-gray-700">
          <section>
            <p className="mb-4">
              Bid The Bezel ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Bid The Bezel.
            </p>
            <p>
              This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, Bid The Bezel. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Definitions and key terms</h2>
            <p className="mb-4">To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
              <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to B Wilder LLC, (150 Seabreeze Blvd Inlet Beach, FL 32461), that is responsible for your information under this Privacy Policy.</li>
              <li><strong>Country:</strong> where Bid The Bezel or the owners/founders of Bid The Bezel are based, in this case is United States</li>
              <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Bid The Bezel Service to manage the relationships with your consumers or service users.</li>
              <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Bid The Bezel and use the services.</li>
              <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
              <li><strong>Personnel:</strong> refers to those individuals who are employed by Bid The Bezel or are under contract to perform a service on behalf of one of the parties.</li>
              <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
              <li><strong>Service:</strong> refers to the service provided by Bid The Bezel as described in the relative terms (if available) and on this platform.</li>
              <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
              <li><strong>Website:</strong> Bid The Bezel's site, which can be accessed via this URL: bidthebezel.com</li>
              <li><strong>You:</strong> a person or entity that is registered with Bid The Bezel to use the Services.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">What Information Do We Collect?</h2>
            <p className="mb-4">We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Name / Username</li>
              <li>Phone Numbers</li>
              <li>Email Addresses</li>
              <li>Mailing Addresses</li>
              <li>Billing Addresses</li>
              <li>Debit/credit card numbers</li>
              <li>Password</li>
            </ul>
            <p className="mb-4">We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
            <p><strong>Photo Gallery (Pictures):</strong> Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this platform.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">When does Bid The Bezel use end user information from third parties?</h2>
            <p>
              Bid The Bezel will collect End User Data necessary to provide the Bid The Bezel services to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Do we share the information we collect with third parties?</h2>
            <p className="mb-4">
              We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
            </p>
            <p className="mb-4">
              We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Use The Information We Collect?</h2>
            <p className="mb-4">Any of the information we collect from you may be used in one of the following ways:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
              <li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</li>
              <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
              <li>To process transactions</li>
              <li>To administer a contest, promotion, survey or other site feature</li>
              <li>To send periodic emails</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Protect Your Information?</h2>
            <p>
              We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Cookies</h2>
            <p className="mb-4">
              Bid The Bezel uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use.
            </p>
            <p>
              However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Kids' Privacy</h2>
            <p>
              We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Changes To Our Privacy Policy</h2>
            <p>
              We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">California Residents</h2>
            <p className="mb-4">The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it. You may exercise the following rights:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Right to Know and Access.</strong> You may submit a verifiable request for information regarding the categories of Personal Information we collect, use, or share.</li>
              <li><strong>Right to Equal Service.</strong> We will not discriminate against you if you exercise your privacy rights.</li>
              <li><strong>Right to Delete.</strong> You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</li>
            </ul>
            <p className="mt-4">We do not sell the Personal Information of our users.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
            <p className="mb-4">Don't hesitate to contact us if you have any questions.</p>
            <ul className="space-y-2">
              <li><strong>Via Email:</strong> zack@bidthebezel.com</li>
              <li><strong>Via Phone number:</strong> 448-238-1122
 </li>
              <li><strong>Via Address:</strong> Inlet Beach, Florida</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
